package hu.bme.aut.android.mymangaapp.model

data class AltTitle (
    val en: String,
    val ru: String,
    val ja: String,
    val ko: String,
    val tr: String,
    val es: String,
    val jaRo: String,
    val pl: String,
    val he: String,
    val ar: String,
    val ms: String,
    val th: String,
    val zh: String,
    val ne: String,
    val vi: String,
    val de: String,
    val fr: String,
    val tl: String,
    val zhHk: String,
    val uk: String,
    val it: String,
    val koRo: String,
    val id: String,
    val la: String,
    val ptBr: String,
)
